apiVersion: v1
kind: Service
metadata:
  name: {{ include "botnetworkpolicy-operator.fullname" . }}-metrics
  labels:
    {{- include "botnetworkpolicy-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: metrics
    port: {{ .Values.metricsPort }}
    targetPort: metrics
    protocol: TCP
  - name: health
    port: {{ .Values.healthPort }}
    targetPort: health
    protocol: TCP
  selector:
    {{- include "botnetworkpolicy-operator.selectorLabels" . | nindent 4 }}
